name: Java CI with Gradle

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: clean build

      - name: Replace gradle properties
        uses: lefherz/action-sed@master
        with:
          args: sed -ie "/version=/ s/=.*/=0.0.4/" ./gradle.properties

      - name: Commit change
        uses: EndBug/add-and-commit@v9
        with:
          message: '[skip ci] Bump gradle.properties'
          add: './gradle.properties'
          cwd: '.'
