name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Chmod gradlew
        run: chmod +x ./gradlew

      - name: Create secrets file
        uses: Amadevus/pwsh-script@v2
          id: script
          with:
            script: |
              Add-Content -Path .\src\main\resources\secrets.properties -Value 'clientId=${{ secrets.CLIENTID }}'
              Add-Content -Path .\src\main\resources\secrets.properties -Value 'clientSecret=${{ secrets.CLIENTSECRET }}'

      - name: Build with Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: clean build

      - name: Publish to Github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
          ./gradlew -Pversion=${RELEASE_VERSION} publishRelease

      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ env.RELEASE_VERSION }}
          version-fragment: 'bug'

      - name: Replace gradle properties
        run: |
          sed -ie "/version=/ s/=.*/=${{ steps.bump_version.outputs.next-version }}/" ./gradle.properties

      - name: Commit change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Bump gradle.properties'
          branch: 'master'
          push_options: '--force'

